### ISSUE TITLE
nbd_connect_tcp: handshake: server policy prevents NBD_OPT_GO

### ISSUE THREAD

**Issue by shemgp** [libguestfs/libnbd#4]
Running `./nbdfuse ../mnt --tcp 172.27.20.55 2222` results in:
```
nbd_connect_tcp: handshake: server policy prevents NBD_OPT_GO

# ./nbdfuse --version
nbdfuse 1.6.1
libnbd 1.7.1
```

With `nbd-server` started on Ubuntu 20.04 with command:
```bash
sudo nbd-server 2222 /dev/md1
```
Please advice what to do. Thanks.

**Comment by rwmjones** [comment]
We're no longer using github (but only changed over today).  In any case I have posted a reply on the mailing list: https://listman.redhat.com/archives/libguestfs/2021-February/msg00022.html
